### ISSUE TITLE
kml/dom/xsd.h no longer installed

### ISSUE THREAD

**Issue by sebastic** [libkml/libkml#212]
The gdal & goldencheetah Debian packages fail to build with libkml 1.3.0-rc1:

```
In file included from /usr/include/kml/dom/element.h:40:0,
                 from /usr/include/kml/dom/object.h:31,
                 from /usr/include/kml/dom/abstractview.h:29,
                 from /usr/include/kml/dom/kmldom.h:29,
                 from /usr/include/kml/dom/kml_cast.h:32,
                 from /usr/include/kml/dom.h:33,
                 from /usr/include/kml/convenience/convenience.h:33,
                 from KmlRideFile.cpp:31:
/usr/include/kml/dom/kml22.h:37:25: fatal error: kml/dom/xsd.h: No such file or directory
```

`kml/dom/xsd.h` was not installed by the old Autotools builds, but shouldn't have been removed in b34517b3545cb6e91563675c0a5b7a5112faf4b2 . Since 73563c403870139d622fe24ae05f8300ecb704a1 `kml/dom/xsd.h` should be installed too.

**Comment by sebastic** [comment]
I think this is pretty bad issue introduced in rc1, so I'd like to see rc2 out soon to have the latest (pre)release work correctly.

@rashadkm, what do you think?

**Comment by rashadkm** [comment]
thanks for the fix. I found this after rc1 yesterday when using it with gdal. There were some other build issues (only on windows). I will fix them and hope to make rc2 this weekend.

**Comment by rashadkm** [comment]
now ready. is it possible to test this on your side before rc2?

**Comment by sebastic** [comment]
I've tested the build of ec60faa, and both gdal & goldencheetah build successfully with it.

The useless whitespace changes made the diff a bit unpleasant to review.

**Comment by rashadkm** [comment]
On 12/1/15, Bas Couwenberg notifications@github.com wrote:

> I've tested the build of ec60faa, and both gdal & goldencheetah build
> successfully with it.

Thanks

> The useless whitespace changes made the diff a bit unpleasant to review.
> 
> sorry it was my editor :(

I will make an rc today evening.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/libkml/libkml/issues/212#issuecomment-160886837

## 

Regards,
   Rashad

**Comment by rashadkm** [comment]
Done. https://github.com/libkml/libkml/releases
