### ISSUE TITLE
minizip fails to compile with version 1.3.0

### ISSUE THREAD

**Issue by LucHermitte** [libkml/libkml#253]
Hi,

In tagged version 1.3.0, the shipped minizip fails to compile as the file `iomem_simple.h` duplicates everything from `ioapi.h` while being both included in the same translation unit.

@rashadkm, I've seen you've patched the file [1] a few weeks after v1.3.0 has been released. Could we have an official v1.3.1 of libkml? (I'm not sure whether master is stable enough for that).

The error being that redeclaring a `typedef` is illegal:

```
[ 24%] Building C object src/kml/base/CMakeFiles/kmlbase.dir/contrib/minizip/unzip.c.o
In file included from $[build}/rh6/libkml-1.3.0/src/kml/base/contrib/minizip/unzip.c:44:
${build}/rh6/libkml-1.3.0/src/kml/base/contrib/minizip/iomem_simple.h:38: error: redefinition of typedef ‘open_file_func’
${prefix}/libkml/1.3.0/include/minizip/ioapi.h:135: note: previous declaration of ‘open_file_func’ was here
... and so on ...
```

NB: it fails with gcc 4.4.7 on RH6, while it compiles with gcc 4.8.5 on RH7. Actually, using gcc 6.3.0 on both RH flavors <del>doesn't change anything. There is something else in my environment which causes different compilation paths on both systems.</del>[EDIT] **changes everything**.

[1] which I'm not sure why it exists in the first place as it's strictly identical to `ioapi.h`.

**Comment by LucHermitte** [comment]
Note however that compilation of master fails with:

```
[ 11%] Building C object CMakeFiles/minizip.dir/unzip.c.o
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c: In function ‘unz64local_GetCurrentFileInfoInternal’:[ 17%] Building C object CMakeFiles/minizip.dir/zip.c.o

/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:893: warning: passing argument 3 of ‘unz64local_getByte’ from incompatible pointer type
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:192: note: expected ‘int *’ but argument is of type ‘uLong *’
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:897: warning: passing argument 3 of ‘unz64local_getByte’ from incompatible pointer type
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:192: note: expected ‘int *’ but argument is of type ‘uLong *’
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:902: warning: passing argument 3 of ‘unz64local_getByte’ from incompatible pointer type
/tmp/cmake-build/third-party/Source/MiniZip/unzip.c:192: note: expected ‘int *’ but argument is of type ‘uLong *’
.
.
.
[ 76%] Built target minizip
Scanning dependencies of target minizipz
Scanning dependencies of target miniunz
[ 88%] Building C object CMakeFiles/miniunz.dir/miniunz.c.o
[ 88%] Building C object CMakeFiles/minizipz.dir/minizip.c.o
[ 94%] Linking C executable minizipz
[100%] Linking C executable miniunz
CMakeFiles/minizipz.dir/minizip.c.o: In function `get_file_crc':
minizip.c:(.text+0xf7): undefined reference to `crc32'
CMakeFiles/minizipz.dir/minizip.c.o: In function `main':
minizip.c:(.text+0x973): undefined reference to `crc32'
libminizip.so.1.2.8: undefined reference to `inflateEnd'
libminizip.so.1.2.8: undefined reference to `deflate'
libminizip.so.1.2.8: undefined reference to `inflateInit2_'
libminizip.so.1.2.8: undefined reference to `inflate'
libminizip.so.1.2.8: undefined reference to `deflateEnd'
libminizip.so.1.2.8: undefined reference to `deflateInit2_'
libminizip.so.1.2.8: undefined reference to `get_crc_table'
collect2: ld returned 1 exit status
make[5]: *** [minizipz] Error 1
make[4]: *** [CMakeFiles/minizipz.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
libminizip.so.1.2.8: undefined reference to `inflateEnd'
libminizip.so.1.2.8: undefined reference to `deflate'
libminizip.so.1.2.8: undefined reference to `inflateInit2_'
libminizip.so.1.2.8: undefined reference to `inflate'
libminizip.so.1.2.8: undefined reference to `crc32'
libminizip.so.1.2.8: undefined reference to `deflateEnd'
libminizip.so.1.2.8: undefined reference to `deflateInit2_'
libminizip.so.1.2.8: undefined reference to `get_crc_table'
collect2: ld returned 1 exit status
make[5]: *** [miniunz] Error 1
make[4]: *** [CMakeFiles/miniunz.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [/tmp/cmake-build/third-party/Stamp/MiniZip/MiniZip-build] Error 2
```

In this case, I've got errors with both my gcc versions.

**Comment by rkanavath** [comment]
can you try this branch?
https://github.com/libkml/libkml/tree/synced_upstream
didn't noticed this bug for a long time. It might have slipped away from me during vacation days.

**Comment by LucHermitte** [comment]
Thanks @rashadkm .
Unfortunately I still have errors.

On my RH6 node, I see the same errors, i.e.:

```
[ 25%] Building C object src/kml/base/CMakeFiles/kmlbase.dir/contrib/minizip/unzip.c.o
In file included from src/kml/base/contrib/minizip/iomem_simple.h:1,
                 from src/kml/base/contrib/minizip/unzip.c:45:
src/kml/base/contrib/minizip/ioapi.h:38: error: redefinition of typedef ‘open_file_func’
third_party/zlib/contrib/minizip/ioapi.h:135: note: previous declaration of ‘open_file_func’ was here
...
```

**Comment by rkanavath** [comment]
I will try to reproduce this locally. what is the compiler on RH6? gcc 4.4.6?.

**Comment by rkanavath** [comment]
i cannot reproduce this with gcc 4.1 or gcc 4.9, 4.8

can you try removing src/kml/base/contrib/minizip/ioapi.h to somewhere else. Because I see this file from new zlib sources have lot of other fixes, starting from the change in header guard defines.

so it might be worth to un-include (if that's a word) this file and try rebuild.

**Comment by Fenrihr** [comment]
> can you try this branch?
> https://github.com/libkml/libkml/tree/synced_upstream
> didn't noticed this bug for a long time. It might have slipped away from me during vacation days.

This branch works for me in Manjaro 18.0.4 (Arch)

**Comment by ramachiranjeevi** [comment]
i am facing this error
1>d:\libkmlsyncedstream\synced_upstream\src\kml\base\contrib\strptime.c(392): error C2065: 'tzname': undeclared identifier
on windows 10

**Comment by pyx26266** [comment]
> i am facing this error
> 1>d:\libkmlsyncedstream\synced_upstream\src\kml\base\contrib\strptime.c(392): error C2065: 'tzname': undeclared identifier
> on windows 10

changing *tzname* to *_tzname* seems to work.
[ref.](https://docs.microsoft.com/en-us/cpp/c-runtime-library/daylight-dstbias-timezone-and-tzname?redirectedfrom=MSDN&view=vs-2019)

**Comment by ryandesign** [comment]
> I've seen you've patched the file [1] a few weeks after v1.3.0 has been released

Specifically it is the first part of d4adfd8a8862ce460314e514b26cffc9815f06ea, in which the function declarations in iomem_simple.h are commented out, that fixes the `redefinition of typedef` error for pre-C11 compilers
